name: ecoplate
channels:
   - conda-forge
dependencies:
   - pandas=2.3.1
   - openpyxl=3.1.5
   - numpy=2.3
   - scipy=1.16.0
   - scikit-learn=1.7.1
   - matplotlib=3.10.5
   - seaborn=0.13.2
   - jupyterlab=4.4.5
